```{r}
library(tidyverse)
library(readr)
library(RColorBrewer)
library(tidytext)
library(wordcloud)
library(tm)
```
```{r}
datos_train <- read.table("datos/drugLibTrain_raw.tsv", sep="\t", comment.char="",quote = "\"", header=TRUE)

#benefits_corpus = Corpus(VectorSource(datos_train$benefitsReview))
#benefits_corpus <- tm_map(benefits_corpus, content_transformer(tolower))
#benefits_corpus <- tm_map(benefits_corpus, content_transformer(removePunctuation))
#benefits_corpus <- tm_map(benefits_corpus, content_transformer(removeWords), stopwords("english"))
#benefits_corpus <- tm_map(benefits_corpus, stripWhitespace)

datos_train$items <- as.character(datos_train$benefitsReview)

```

```{r}
drugstext <- unnest_tokens(datos_train, word, items)

binarytextscore <- get_sentiments(lexicon = "bing")
    
drugscloudbinary <- drugstext %>%
    inner_join(binarytextscore, by = "word") %>%
    count(word, sentiment) %>%
    mutate(color = ifelse(sentiment == "positive", "darkgreen", "red"))

wordcloud(drugscloudbinary$word, drugscloudbinary$n, random.order = FALSE, colors = drugscloudbinary$color, ordered.colors = TRUE)
```



