---
title: "K_means"
output: html_document
---


```{r}
library(tm)
library(factoextra)

# Cargamos los tados
datos_train <- read.table("../datos/drugLibTrain_raw.tsv", sep="\t", comment.char="",quote = "\"", header=TRUE)
# Establecemos la semilla
set.seed(3)

# Utilizamos números en vez de texto
datos_train$sideEffectsNumber[datos_train$sideEffects=="Extremely Severe Side Effects"]<-5
datos_train$sideEffectsNumber[datos_train$sideEffects=="Severe Side Effects"]<-4
datos_train$sideEffectsNumber[datos_train$sideEffects=="Moderate Side Effects"] <- 3
datos_train$sideEffectsNumber[datos_train$sideEffects=="Mild Side Effects"]<- 2
datos_train$sideEffectsNumber[datos_train$sideEffects=="No Side Effects"]<- 1

datos_train$effectivenessNumber[datos_train$effectiveness=="Highly Effective"]<-5
datos_train$effectivenessNumber[datos_train$effectiveness=="Considerably Effective"]<-4
datos_train$effectivenessNumber[datos_train$effectiveness=="Moderately Effective"]<-3
datos_train$effectivenessNumber[datos_train$effectiveness=="Marginally Effective"]<-2
datos_train$effectivenessNumber[datos_train$effectiveness=="Ineffective"]<- 1

datos_train = datos_train[-1]
datos_train2 = datos_train[c(2,9,10)]
head(datos_train2)

```

```{r}

# Hay valores perdidos
benefits_corpus = Corpus(VectorSource(datos_train))
benefits_corpus <- tm_map(benefits_corpus, content_transformer(tolower))
benefits_corpus <- tm_map(benefits_corpus, content_transformer(removePunctuation))
benefits_corpus <- tm_map(benefits_corpus, content_transformer(removeWords), stopwords("english"))
benefits_corpus <- tm_map(benefits_corpus, stripWhitespace)
# https://github.com/joseangeldiazg/twitter-text-mining/blob/master/ner.R
# Localizamos posibles valores perdidos que se hayan generado tras el proceso de limpieza

# Vemos que no hay muchos vacios 
benefits_corpus<-benefits_corpus[which(benefits_corpus$content!="")]
benefits_corpus<-benefits_corpus[which(benefits_corpus$content!=" ")]
benefits_corpus<-benefits_corpus[which(benefits_corpus$content!="  ")]
benefits_corpus<-benefits_corpus[which(benefits_corpus$content!="   ")]

# Aplicamos la tecnica
km.res <- kmeans(benefits_corpus, 4, 25)

print(km.res)

```

